name: Maven Package Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, macos]
    outputs:
      artifact-path: ${{ steps.set-path.outputs.artifact_path }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Maven package
      id: build
      run: mvn clean package -DskipTests

    - name: Set artifact path output
      id: set-path
      run: echo "::set-output name=artifact_path::target/*.jar"

  archive-artifacts:
    needs: build
    runs-on: [self-hosted, macos]

    steps:
    - name: Download source (required in separate job)
      uses: actions/checkout@v3

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: maven-package
        path: target/*.jar
