name: Maven Package Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, macos]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Maven package
      run: mvn clean package -DskipTests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-package
        path: target/*.jar

  archive-artifacts:
    needs: build
    runs-on: [self-hosted, macos]

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: maven-package
        path: ./target

    - name: List downloaded artifacts
      run: ls -l target/
